#!/usr/bin/env bash
# Prove that StaffSwipe's production-compatible SQL+gzip backup format can be
# restored. This script is intentionally destructive ONLY to databases it
# creates itself; never point it at a production database.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP_DIR="$(mktemp -d)"
SUFFIX="${GITHUB_RUN_ID:-local}_$$_${RANDOM}"
SOURCE_DB="staffswipe_recovery_src_${SUFFIX}"
RESTORE_DB="staffswipe_recovery_dst_${SUFFIX}"
DUMP="$TMP_DIR/staffswipe.sql.gz"
CORRUPT="$TMP_DIR/corrupt.sql.gz"
SENTINEL="staffswipe_restore_${SUFFIX}"

: "${PGHOST:=localhost}"
: "${PGPORT:=5432}"
: "${PGUSER:=postgres}"
export PGHOST PGPORT PGUSER

cleanup() {
  # These names are generated by this script, so cleanup cannot target the
  # caller's real StaffSwipe database.
  dropdb --if-exists "$RESTORE_DB" >/dev/null 2>&1 || true
  dropdb --if-exists "$SOURCE_DB" >/dev/null 2>&1 || true
  rm -rf "$TMP_DIR"
}
trap cleanup EXIT

for cmd in createdb dropdb pg_dump psql gzip; do
  command -v "$cmd" >/dev/null 2>&1 || {
    echo "required command missing: $cmd" >&2
    exit 1
  }
done

echo "[recovery] creating disposable source database"
createdb "$SOURCE_DB"

# Apply the exact Alembic chain used in production. Secrets below are throwaway
# process-local test values; the database itself is disposable.
(
  cd "$ROOT/backend"
  DATABASE_URL="postgresql+psycopg://${PGUSER}:${PGPASSWORD:-}@${PGHOST}:${PGPORT}/${SOURCE_DB}" \
  DEV_MODE=true \
  JWT_SECRET="recovery-ci-jwt-secret-not-production" \
  INTERNAL_API_SECRET="recovery-ci-internal-secret-not-production" \
  python -m alembic upgrade head
)

# Dedicated sentinel avoids coupling the restore proof to required marketplace
# fields while still proving that arbitrary application data survives.
psql -v ON_ERROR_STOP=1 -d "$SOURCE_DB" <<SQL
CREATE TABLE staffswipe_restore_sentinel (
  marker text PRIMARY KEY
);
INSERT INTO staffswipe_restore_sentinel(marker) VALUES ('$SENTINEL');
SQL

echo "[recovery] dumping with production-compatible SQL + gzip semantics"
pg_dump --clean --if-exists "$SOURCE_DB" | gzip -9 > "$DUMP"
gzip -t "$DUMP"

# Negative proof: a verifier that accepts a damaged archive gives false safety.
# This corrupt archive must fail gzip integrity validation.
head -c 8 "$DUMP" > "$CORRUPT"
if gzip -t "$CORRUPT" 2>/dev/null; then
  echo "corrupt archive check must fail, but it passed" >&2
  exit 1
else
  echo "[recovery] corrupt archive check must fail: correctly rejected"
fi

echo "[recovery] restoring into a second empty disposable database"
createdb "$RESTORE_DB"
gzip -dc "$DUMP" | psql -v ON_ERROR_STOP=1 -d "$RESTORE_DB" >/dev/null

# Core schema plus sentinel data must both survive. to_regclass avoids exposing
# any data and fails cleanly when a table is absent.
CORE_TABLE="$(psql -At -v ON_ERROR_STOP=1 -d "$RESTORE_DB" -c "SELECT to_regclass('public.users')::text")"
if [[ "$CORE_TABLE" != "users" ]]; then
  echo "restored database is missing core users table" >&2
  exit 1
fi

SENTINEL_COUNT="$(psql -At -v ON_ERROR_STOP=1 -d "$RESTORE_DB" -c "SELECT count(*) FROM staffswipe_restore_sentinel WHERE marker = '$SENTINEL'")"
if [[ "$SENTINEL_COUNT" != "1" ]]; then
  echo "restored database is missing sentinel data" >&2
  exit 1
fi

echo "[recovery] ✅ dump, gzip integrity, restore, schema and sentinel verified"
