"""add blocked flag

Revision ID: 52f24481daa9
Revises: 0c0ddf98d3eb
Create Date: 2026-06-21 00:51:20.421333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f24481daa9'
down_revision: Union[str, Sequence[str], None] = '0c0ddf98d3eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employers', sa.Column('blocked', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('blocked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blocked')
    op.drop_column('employers', 'blocked')
    # ### end Alembic commands ###
